### ISSUE TITLE
Setup PRs?

### ISSUE THREAD

**Issue by coatless** [ivan-pavlov/rvwgsoc#1]
@ivan-pavlov, you're doing a great job on the `develop` line. 

Would it be possible to slowly start to do PRs into the master? I think this would make it easier to do code reviews and have testable nightly builds for us to explore.

**Comment by ivan-pavlov** [comment]
Yes, sure, thank you!

I still experimenting with External Pointers implementation of VW object, but I will finish that soon. And start using PR for the main version of a package.

**Comment by eddelbuettel** [comment]
I think we can close this now.
