### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by aotto11235** [ivan-pavlov/rvwgsoc#17]
This library looks like a great improvement over the long standing legacy version. While I am trying to install this the following error pops up:

g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG -Iextra/ -I/usr/local/include/vowpalwabbit -I"/home/MYNAME/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/MYNAME/R/i686-pc-linux-gnu-library/3.4/RApiSerialize/include"    -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c helpers.cpp -o helpers.o
helpers.cpp: In function ‘vw* setup_model(std::string)’:
helpers.cpp:172:63: error: ‘struct vw’ has no member named ‘opts_n_args’
     if (!all->quiet && !all->bfgs && !all->searchstr && !all->opts_n_args.vm.count("audit_regressor"))
                                                               ^
helpers.cpp: In function ‘bool copy_get_best_constant(vw&, float&, float&)’:
helpers.cpp:283:33: error: ‘struct vw’ has no member named ‘opts_n_args’
     po::variables_map& vm = all.opts_n_args.vm;
                                 ^
make: *** [helpers.o] Error 1
ERROR: compilation failed for package ‘rvw’

/usr/local/include/vowpalwabbit has all the header files on my machine (vw.h and global_data.h) where the opts_n_args member is defined.  FYI I have vw 8.6.1 too. Any idea why this isn't compiling correctly?

**Comment by eddelbuettel** [comment]
What OS do you use?   We had to accomodate some platforms because, as I recall, `make install` for Vowpal Wabbit did not copy enough.

**Comment by coatless** [comment]
That is indeed the case: https://github.com/rvw-org/rvw/pull/10#issuecomment-412393785 

No update on the upstream ticket: https://github.com/VowpalWabbit/vowpal_wabbit/issues/1567

**Comment by aotto11235** [comment]
I'm on Ubuntu. Thanks @coatless for pointing this upstream issue out.

**Comment by eddelbuettel** [comment]
_Which_ Ubuntu version?  I am on Ubuntu too, have been for years and have no (besides the known one here).

Try copying the missing files from the VW source tarball (of the same version) into `/usr/include/vowpalwabbit`.  I _think_ @ivan-pavlov set it up to accomodate this in the package which  also ships some missing headers.

**Comment by aotto11235** [comment]
Sorry about that, this is on Ubuntu 14.04.5 LTS. I copied over the files as suggested and it seems like everything is working now. Thanks for the help!
