### ISSUE TITLE
Please add a vignette or demo

### ISSUE THREAD

**Issue by eddelbuettel** [ivan-pavlov/rvwgsoc#3]
Right now the only way to look at how to _run_ any of this is via the tests.  That is not good enough.

**Comment by coatless** [comment]
Also, could you add documentation for each function using [`roxygen2`](https://CRAN.R-project.org/package=roxygen2)? This is particularly important for having the package get added onto CRAN.

For help with `roxygen2`, I would recommend reading:

- [Generating Rds](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html)
- [Writing in Markdown](https://cran.r-project.org/web/packages/roxygen2/vignettes/markdown.html)

**Comment by eddelbuettel** [comment]
>  This is particularly important for having the package get added onto CRAN.

It is important to have documentation. It is not required to use `roxygen2` -- many of us like it though. I still don't use it with markdown.  Old habits and all that...

**Comment by eddelbuettel** [comment]
This can be closed.
